crowdcomputer/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from api.views import router, task_router


admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^api2/', include(router.urls)),
                       url(r'^api2/', include(task_router.urls)),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^exe', include('executor.urls')),
                       # url(r'^mt', include('mturk.urls')),
                       url(r'^req', include('requester.urls')),
                       url(r'^api/', include('restapi.urls')),
                       url(r'^dev/', include('developer.urls')),
                       #    url(r'^bpmn/', include('bpmn.urls')),
                       url(r'^', include('general.urls')),
                       url(r'', include('social_auth.urls')),

)
urlpatterns += patterns('django.contrib.flatpages.views',
                        (r'^(?P<url>.*)$', 'flatpage'),
)

general/urls.py
from django.conf.urls import patterns, url
from django.views.generic.base import TemplateView
from general import views

urlpatterns = patterns('',
	url(r'^geoloc/updateloc/$', views.UpdateLoc, name='updateloc'),
    url(r'^geoloc/$', views.GeoLoc, name='geoloc'),
    url(r'^geoloc/more$', views.AddGeoLoc, name='addgeoloc'),
    url(r'^create/$', views.CreateUser, name='register'),
    url(r'^profile/$', views.ProfileView, name='profile'),
    url(r'^login/$', views.Login, name='login'),
    url(r'^apilogin/$', views.ApiLogin, name='apilogin'),
    url(r'^logout/$', views.Logout, name='logout'),
    url(r'^thanks/$', TemplateView.as_view(template_name='general/thanks.html'), name='thanks'),
#    url(r'^$',redirect_to, {'url':reverse_lazy('e-list')}),
    url(r'^$', TemplateView.as_view(template_name="general/home.html"), name='home'),
    )

requester/urls.py
from django.conf.urls import patterns, url
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required
from requester import views

urlpatterns = patterns('',
    url(r'^/$', login_required(TemplateView.as_view(template_name="requester/home.html")), name='r-home'),
    #----------------------------------------------------------------------------------------------------------------------
    url(r'^/process/(?P<process_id>\d+)/task/create/task/$', login_required(views.TaskCreationHub.as_view()), name='r-task-create'),
    url(r'^/process/(?P<process_id>\d+)/task/create/human/$', login_required(views.HumanTaskCreation.as_view()), name='r-task-create-human'),
    url(r'^/process/(?P<process_id>\d+)/task/create/machine/$', login_required(views.MachineTaskCreation.as_view()), name='r-task-create-machine'),
   # url(r'^/process/(?P<process_id>\d+)/task/create/splitdata/$', login_required(views.SplitDataTaskCreation.as_view()), name='r-task-create-splitdata'),
   # url(r'^/process/(?P<process_id>\d+)/task/create/filterdata/$', login_required(views.FilterDataTaskCreation.as_view()), name='r-task-create-filterdata'),
    
    #----------------------------------------------------------------------------------------------------------------------  
    url(r'^/process/(?P<pk>\d+)/update/$', login_required(views.ProcessUpdate.as_view()), name='r-process-update'),
    url(r'^/process/(?P<process_id>\d+)/delete/$', views.ProcessDelete, name='r-process-delete'),
    url(r'^/process/(?P<process_id>\d+)/start/$', views.ProcessStart, name='r-process-start'),
    url(r'^/process/(?P<process_id>\d+)/stop/$', views.ProcessStop, name='r-process-stop'),
    url(r'^/process/create/$', login_required(views.ProcessCreation.as_view()), name='r-process-create'),
    url(r'^/processes/$', login_required(views.ProcessList.as_view()), name='r-process'),
    url(r'^/process/(?P<process_id>\d+)/tasklist/$', login_required(views.TaskList.as_view()), name='r-task-list'),
#    url(r'^/confirmation/$', login_required(views.Confirmation.as_view()), name='r-confirmation'),

#    url(r'^/process/(?P<process_id>\d+)/tasklist/(?P<prev_process_id>\d+)/(?P<prev_task_id>\d+)/$', login_required(views.TaskList.as_view()), name='r-task-list-validation'),

#    url(r'^/task/create/$', views.TaskCreation, name='r-task-create'),
    url(r'^/process/(?P<process_id>\d+)/task/(?P<pk>\d+)/update/$', login_required(views.TaskUpdate.as_view()), name='r-task-update'),
    url(r'^/process/(?P<process_id>\d+)/task/(?P<task_id>\d+)/cvs/$', views.exportcsv, name='r-task-csv'),

    url(r'^/process/(?P<process_id>\d+)/task/(?P<task_id>\d+)/taskinstances/$', login_required(views.TaskInstanceList.as_view()), name='r-taskinstances'),

    url(r'^/process/(?P<process_id>\d+)/task/(?P<task_id>\d+)/delete/$', views.TaskDelete, name='r-task-delete'),
    url(r'^/process/(?P<process_id>\d+)/task/(?P<task_id>\d+)/start/$', views.TaskStartStop, name='r-task-start'),
    url(r'^/process/(?P<process_id>\d+)/task/(?P<task_id>\d+)/stop/$', views.TaskStop, name='r-task-stop'),

    url(r'^/process/upload/$', views.uploadProcess, name='bpmn-upload'),

    # better without many nesting
    url(r'^/task/(?P<task_id>\d+)/validate/$', login_required(views.TaskValidate), name='r-task-validate'),
    url(r'^/taskinstance/(?P<task_instance_id>\d+)/validate/$', login_required(views.TaskInstanceValidate), name='r-taskinstance-validate'),



#    url(r'^/process/(?P<process_id>\d+)/task/(?P<task_id>\d+)/finish/$', views.TaskFinish, name='r-task-finish'),

    )

requester/forms.py
from django import forms
from datetime import date, timedelta
from general.models import Task, Process, Application, HumanTask, \
    Reward, ValidationTask, MachineTask
    # SplitDataTask, FilterDataTask, 
from django.contrib.auth.models import User
from django.forms import ModelForm
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Fieldset, Layout
import general
import logging
from general import utils
from decimal import Decimal
from django.utils.datetime_safe import datetime
from django.forms.forms import Form
from django.forms.fields import FileField

log = logging.getLogger(__name__)

class ProcessForm(ModelForm):
    title = forms.CharField(label=(u'Process name'))
    description = forms.CharField(label=(u'Process description'), widget=forms.Textarea())
    owner = forms.ModelChoiceField(queryset=User.objects.all(), widget=forms.HiddenInput)
    application = forms.ModelChoiceField(queryset=Application.objects.all(), widget=forms.HiddenInput)
    
    class Meta:
        model = Process
        exclude = ('date_created', 'status',)

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save'))
        self.helper.form_class = 'form-horizontal'
        super(ProcessForm, self).__init__(*args, **kwargs)




   
# TODO: there should be a smarter way to do this.
class ValidationForm(ModelForm):
    owner = forms.ModelChoiceField(queryset=User.objects.all(), widget=forms.HiddenInput)
    process = forms.ModelChoiceField(queryset=Process.objects.all(), widget=forms.HiddenInput)

    class Meta:
        model = ValidationTask
        exclude = ('to_validate',) + ('parameters', 'status', 'objects', 'date_deadline', 'date_created')

# TODO: there should be a smarter way to do this.  
class HumanTaskForm(ModelForm):
    owner = forms.ModelChoiceField(queryset=User.objects.all(), widget=forms.HiddenInput)
    process = forms.ModelChoiceField(queryset=Process.objects.all(), widget=forms.HiddenInput)
    title = forms.CharField(label=(u'Task name'))
    description = forms.CharField(label=(u'Task description'), widget=forms.Textarea())
    page_url = forms.CharField(label=(u'A url of the task web form'), required=True)
    platfom = forms.ChoiceField(choices=general.models.PLATFORMS, widget=forms.Select(), label=(u'Platform where to deploy'), required=False)
    date_deadline = forms.DateTimeField(label=(u'Deadline (DD/MM/YYYY HH:MM)'), initial=lambda: (datetime.now() + timedelta(days=7)), widget=forms.DateTimeInput(format='%d/%m/%Y %H:%M'), input_formats=('%d/%m/%Y %H:%M',))
    number_of_instances = forms.IntegerField(label=(u'Number of assignments per Task'), required=True, initial=1)
    type = forms.ChoiceField(choices=general.models.REWARDS, widget=forms.Select(), label=(u'Reward Type'), required=True)
    quantity = forms.DecimalField(decimal_places=2, max_digits=8, required=True, initial=Decimal('0.00'))

    class Meta:
        model = HumanTask
        exclude = ('parameters', 'status', 'objects', 'date_deadline', 'date_created') + ('uuid', 'reward')
    
    def clean_quantity(self):
        data = self.cleaned_data['quantity']
        log.debug('%s' % data)
        if data < 0:
            raise forms.ValidationError("C'mon, value must be > 0")
        return data
     
    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save'))
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(Fieldset('Human Task', 'owner', 'process', 'title', 'description', 'platform', 'page_url', 'number_of_instances', 'date_deadline', 'type', 'quantity'))
        super(HumanTaskForm, self).__init__(*args, **kwargs)

class MachineTaskForm(ModelForm):
    owner = forms.ModelChoiceField(queryset=User.objects.all(), widget=forms.HiddenInput)
    process = forms.ModelChoiceField(queryset=Process.objects.all(), widget=forms.HiddenInput)
    title = forms.CharField(label=(u'Task name'))
    description = forms.CharField(label=(u'Task description'), widget=forms.Textarea())
    date_deadline = forms.DateTimeField(label=(u'Deadline (DD/MM/YYYY HH:MM)'), initial=lambda: (datetime.now() + timedelta(days=7)), widget=forms.DateTimeInput(format='%d/%m/%Y %H:%M'), input_formats=('%d/%m/%Y %H:%M',))
    service_url = forms.CharField(label=(u'The url of the service'), required=True)

   
    class Meta:
        model = MachineTask
        exclude = ('parameters', 'status', 'objects', 'date_deadline', 'date_created')
    
    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save'))
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(Fieldset('Machine Task', 'owner', 'process', 'title', 'description', 'service_url', 'date_deadline'))
        super(MachineTaskForm, self).__init__(*args, **kwargs)
        

class UploadFileForm(Form):
    file  = FileField()
    
    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save'))
        self.helper.form_class = 'form-horizontal'
        super(UploadFileForm, self).__init__(*args, **kwargs)
        
class ValidationForm(Form):
    validation = forms.IntegerField(max_value=100,min_value=0)

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save'))
        self.helper.form_class = 'form-horizontal'
        super(ValidationForm, self).__init__(*args, **kwargs)

'''
class SplitDataTaskForm(ModelForm):
    owner = forms.ModelChoiceField(queryset=User.objects.all(), widget=forms.HiddenInput)
    process = forms.ModelChoiceField(queryset=Process.objects.all(), widget=forms.HiddenInput)
    title = forms.CharField(label=(u'Operation name'))
    description = forms.CharField(label=(u'Task description'), initial='task description', widget=forms.HiddenInput)
    date_deadline = forms.DateTimeField(label=(u'Deadline (DD/MM/YYYY HH:MM)'), initial=lambda: (datetime.now() + timedelta(days=7)), widget=forms.HiddenInput) # widget=forms.DateTimeInput(format='%d/%m/%Y %H:%M'), input_formats=('%d/%m/%Y %H:%M',))
    split = forms.ChoiceField(choices=general.models.SPLIT_CHOICE, widget=forms.Select(), label=(u'Split option'), required=False)
    
    class Meta:
        model = SplitDataTask
        exclude = ('parameters', 'status', 'objects')
    
    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save'))
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(Fieldset('SplitData Operation', 'owner', 'process', 'title', 'split', 'split_field_N', 'split_field_M','date_deadline', 'description'))
        super(SplitDataTaskForm, self).__init__(*args, **kwargs)
class FilterDataTaskForm(ModelForm):
    owner = forms.ModelChoiceField(queryset=User.objects.all(), widget=forms.HiddenInput)
    process = forms.ModelChoiceField(queryset=Process.objects.all(), widget=forms.HiddenInput)
    title = forms.CharField(label=(u'Operation name'))
    description = forms.CharField(label=(u'Task description'), initial='task description', widget=forms.HiddenInput)
    date_deadline = forms.DateTimeField(label=(u'Deadline (DD/MM/YYYY HH:MM)'), initial=lambda: (datetime.now() + timedelta(days=7)), widget=forms.HiddenInput) # widget=forms.DateTimeInput(format='%d/%m/%Y %H:%M'), input_formats=('%d/%m/%Y %H:%M',))
    filter = forms.ChoiceField(choices=general.models.FILTER_CHOICE, widget=forms.Select(), label=(u'Filter option'), required=False)
    class Meta:
        model = FilterDataTask
        exclude = ('parameters', 'status', 'objects')
    
    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save'))
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(Fieldset('FilterData Operation', 'owner', 'process', 'title', 'filter', 'filter_field', 'filter_value', 'filter_exclude', 'date_deadline', 'description'))
        super(FilterDataTaskForm, self).__init__(*args, **kwargs)

'''
#class HumanTaskForm(TaskForm,ModelForm):
#    owner = forms.ModelChoiceField(queryset=User.objects.all(),widget=forms.HiddenInput)
#    process = forms.ModelChoiceField(queryset=Process.objects.all(),widget=forms.HiddenInput)
#    class Meta:
#        model= HumanTask
#        exclude = ('uuid','reward')
    
#    def __init__(self, *args, **kwargs):
#        super(HumanTaskForm, self).__init__(*args, **kwargs)
#        log.debug(self.fields)
#        validationForm = ValidationForm(prefix="validation")
#        for v in validationForm.fields:
#            log.debug("%s " %(v))
#        self.fields (validationForm.fields)
#        log.debug(self.fields)     
     
#class FullHumanTaskForm(ValidationForm,RewardForm,HumanTaskForm):
##    pass
#    def __init__(self, *args, **kwargs):
##        ModelForm.__init__(self, *args, **kwargs) # Call the constructor of ModelForm
#        RewardForm.__init__(self, *args, **kwargs) # Call the constructor of polo
#        ValidationForm.__init__(self, *args, **kwargs)
#        HumanTaskForm.__init__(self, *args, **kwargs)

#class TaskForm(ModelForm):
#    title = forms.CharField(label=(u'Task name'))
#    description = forms.CharField(label=(u'Task description'), widget=forms.Textarea())
#    input_url = forms.CharField(label=(u'A url of the task web form'), required=True)

requester/templates/requester/base.html
{% load static from staticfiles %}
{% load gravatar %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title> {{ app_name}} {%block pagetitle %}{% endblock %}</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="">
		<meta name="author" content="Stefano Tranquillini">
		<meta name="keywords" content="">
		<!-- Le styles -->
		<link rel="icon"
		type="image/png"
		href="{% static "img/icon.png" %}">
		<link href="{% static "css/bootstrap.css" %}" rel="stylesheet">
		<link rel="stylesheet" href="{% static "css/font-awesome.css" %}">
		<link rel="stylesheet" href="{% static "css/style.css" %}">
		<!--script src="http://code.jquery.com/jquery-latest.js"></script-->
		<script src="http://dev.kucherbaev.com/jquery/jquery-1.7.2.min.js"></script>

		<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
		<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->

		<!-- Le fav and touch icons -->
		{%block script_head %}

		{% endblock %}
	</head>

	<body>

		<div class="navbar navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">

					<!-- .btn-navbar is used as the toggle for collapsed navbar content -->
					<a class="btn btn-navbar" href='#' data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span> <!--> <span class="icon-bar"></span><span class="icon-bar"></span> --> </a>

					<!-- Be sure to leave the brand out there if you want it shown -->
					<a href="/" class="brand">{{ app_name}}</a>

					<!-- Everything you want hidden at 940px or less, place within here -->

					<div class="nav-collapse">
						<ul class="nav  pull-right">
							<!-- this user is the one from django.contrib.auth -->
							<li>
								<a href="{% url "r-process" %}">Processes</a>
							</li>
							<li class="divider"></li>
							<li class="dropdown">
								<a class="dropdown-toggle" data-toggle="dropdown" href="#"><img src="{% gravatar_for_email user.email 25 %}" class="img-circle" />{{user.first_name}}.{{user.last_name}}<b class="caret"></b></a>
								<ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
									<li>
										<a href="{% url "profile" %}">Profile</a>
									</li>
									<li>
										<a href="/logout/">Logout</a>
									</li>
								</ul>

							</li>
						</ul>
					</div>
				</div>

			</div>
		</div>
		<div id="wrap">
			<div class="container">
				{% if messages %}
				{% for message in messages %}
				<div class="alert alert-{{message.tags}} fade in">
					<button type="button" class="close" data-dismiss="alert">
						&times;
					</button>
					<h2>Attention!</h2>
					{{ message }}
				</div>
				{% endfor %}
				{% endif %}
				{%block container %}

				{% endblock %}

			</div>
			<div class="modal" id="Modal" style="display:none;">
				<div class="modal-header">
					<button class="close" data-dismiss="modal">
						×
					</button>
					<h3></h3>
				</div>
				<div class="modal-body"></div>
				<div class="modal-footer">
					<button class="btn btn-success" data-dismiss="modal">
						ok
					</button>
				</div>
			</div>

			<!--link rel="stylesheet" href="{% static "css/demo.css" %}" type="text/css" media="screen">
			<link rel="stylesheet" href="{% static "css/demo-print.css" %}" type="text/css" media="print"-->

			<script src="{% static "js/bootstrap.js" %}"></script>
			<script>
				// may be we can simplified- but now I don't know how to get the address of static in javascript
				var static = "{% static "" %}";
				$(document).ready(function() {
					$('.tip').tooltip();
					$('.btn').tooltip();
				});
			</script>
			<script src="{% static "js/modals.js" %}"></script>
			<script src="{% static "js/ajaxSecurity.js" %}"></script>
			<script src="{% static "js/markdown.js" %}"></script>
			<!--script src="{% static "js/postMessage.min.js" %}"></script-->
		</div>
		{%block script_footer %}

		{% endblock %}
		{% include 'footer.html' %}
	</body>
</html>

requester/templates/requester/confirm.html
{% extends 'requester/base.html' %}
{% load myfilters %}
{% load humanize %}

{% block pagetitle %}  {% endblock %}

{% block container %}

{% if process %}
<h1>Are you sure to stop the process {{ process.title }} </h1>
<form action="{% url 'r-process-stop' process.pk %}" method="post">
{% csrf_token %}
<input type="submit" value="Yes">
</form> 
<form action="{% url 'r-process' %}" method="get">
<input type="submit" value="No">
</form>
{%else%}
<h1>Are you sure to stop the task {{ task.title }} </h1>

<form action="{% url 'r-task-stop' task.process.pk task.pk %}" method="post">
{% csrf_token %}
<input type="submit" value="Yes">
</form> 
<form action="{% url 'r-task-list' task.process.pk %}" method="get">
<input type="submit" value="No">
</form>
{%endif%}
{% endblock %}

requester/templates/requester/creation.html
{% extends 'requester/base.html' %} 
{% load crispy_forms_tags %}
{% block pagetitle %} Create {% endblock %}
{% block container %}
    {% crispy form %}

{% endblock %}

{% block script_footer %}
<script>
/*
function hide(field){
	console.log(field.is(":visible"));
	if (field.is(":visible")){
				console.log('hiding');
		 		field.slideToggle(100);
			} 
}

function show(field){
	if (!(field.is(":visible"))){
		 		field.slideToggle(100);
			} 
}

function show_hide_input_task_field() {	
	//this hides and shows the split method
	var value = $("#id_category").val();
	//if not a machine task then show the splitting
	if ((($('#div_id_input_task input:checked')).length>0) && (value=='HT')){
	 	show($("#div_id_split"));
	 	show_hide_input_task_N_M_fields();
	}	
	else {
		hide($("#div_id_split"));
		$("#div_id_split_field_N").hide();
		$("#div_id_split_field_M").hide();
	}

 	//this hides and shows the id for merging
 	if (($('#div_id_input_task input:checked')).length>1){
	 	show($("#div_id_input_task_field"));
	 	
	}	
	else {
		hide($("#div_id_input_task_field"));
	}
	
	//this should show the fields depending on the type chosen in the div_id_split
 
};


function show_hide_input_task_N_M_fields(){
	//if split is visible
	if (($("#div_id_split")).is(":visible")){
		var value = $("#id_split").val();
		//split in N
		if (value==2 || value==4){
			show($("#div_id_split_field_N"));
			hide($("#div_id_split_field_M"));
			
		}else
			//split in N.M
			if (value==3){
				show($("#div_id_split_field_N"));
				show($("#div_id_split_field_M"));
			}
			else{
				hide($("#div_id_split_field_N"));
				hide($("#div_id_split_field_M"));
			}
	}
	else{
			hide($("#div_id_split_field_N"));
			hide($("#div_id_split_field_M"));
		}
};

function show_hide_rr(){
	var value = $("#id_category").val();
	if (value=="HT"){
		show($("#div_id_instances_required"));
		show($("#div_id_is_unique"));
		show($("#div_id_isMturk"));
		show($("#div_id_reward_mturk"));
		show($("#div_id_date_deadline"));
		show($("#div_id_reward_type"));
		show($("#div_id_reward_quantity"));
	}		
	else{
		hide($("#div_id_instances_required"));
		hide($("#div_id_is_unique"));
		hide($("#div_id_isMturk"));
		hide($("#div_id_reward_mturk"));
		hide($("#div_id_date_deadline"));
		hide($("#div_id_reward_type"));
		hide($("#div_id_reward_quantity"));
	}
};

function show_hide_all(){
	show_hide_rr();
	show_hide_input_task_field();
	show_hide_input_task_N_M_fields();
};

function show_hide_mturk(){
	var value = $("#id_isMturk").val();
	console.log(value);
	//True is not true
	if (value=='True'){
		show($("#div_id_reward_mturk"));
	}		
	else{
		hide($("#div_id_reward_mturk"));
	}		
};



$("#div_id_input_task").click(show_hide_input_task_field);
$('#id_split').change(show_hide_input_task_N_M_fields);
$("#id_category").change(show_hide_all);
$("#id_isMturk").change(show_hide_mturk);


$(document).ready(function() {
  show_hide_rr();
  show_hide_input_task_field();
  show_hide_input_task_N_M_fields();
  hide($("#div_id_reward_mturk"));
});
*/
</script>
{% endblock %}

 

requester/templates/requester/creation_bpmn.html
{% extends 'requester/base.html' %} 
{% load crispy_forms_tags %}
{% block pagetitle %} Create {% endblock %}
{% block container %}
    {% crispy form %}

{% endblock %}

{% block script_footer %}
<script>

</script>
{% endblock %}

 

requester/templates/requester/form.html
{% extends 'requester/base.html' %} 
{% load crispy_forms_tags %}
{% block pagetitle %} Form {% endblock %}
{% block container %}
    {% crispy form %}

{% endblock %}

{% block script_footer %}
<script>
</script>
{% endblock %}

 

requester/templates/requester/home.html
{% extends 'requester/base.html' %} 
{% block pagetitle %} Home {% endblock %}

{% block container %}
<h1>{{ app_name}}</h1>
<p>description of this wonderful project</p>
{% endblock %}

requester/templates/requester/process_list.html
{% extends 'requester/base.html' %}
{% load myfilters %}
{% load humanize %}

{% block pagetitle %} Profile {% endblock %}

{% block container %}

    <h1>Processes created by you <a href="{% url "bpmn-upload" %}" title='add a new process' class="btn"><i
            class="icon-plus"></i></a></h1>
    <div class='row'>
        <table class="table table-hover ">
            <thead>
            <th>Title</th>
            <th>Description</th>
            <th>Status</th>
            <th>Date</th>
            <th></th>
            </thead>
            {% for process in process_list %}
                {% if  process.parameters.display != False %}
                    <tr class="{{ process.status|to_tr_class }}">

                        <td>{{ process.title }}</td>
                        <td>{{ process.description }}</td>
                        {% if process %}
                            <td>{{ process.status }}</td>
                        {% endif %}
                        <td>{{ process.date_created }}</td>

                        <td>
                            <div class="btn-group">
                                <!--  FIXME: make a control here -->
                                <a href='{% url "r-task-list" process.id %}' class='btn'
                                   title='show tasks in this process'><i class='icon-th-list'></i></a>
                                {% if process.is_inprocess %}
                                    <a href='{% url "r-process-stop" process.id %}' class='btn' title='Force finish'><i
                                            class='icon-ok'></i></a>
                                {% endif %}
                                {% if False %}
                                    <a href='{% url "r-process-update" process.id %}' class='btn'
                                       title='edit this process'><i class='icon-pencil'></i></a>

                                    <a href='{% url "r-process-delete" process.id %}' class='btn btn-danger'
                                       title='delete this process'><i class='icon-trash'></i></a>
                                {% endif %}
                            </div>
                        </td>

                    </tr>
                {% endif %}
            {% endfor %}

        </table>
        {% if is_paginated %}
            <div class="pagination pagination-centered">
                <ul>
                    {% if page_obj.has_previous %}
                        <li class="active"><a
                                href="{% url "r-process" %}?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                    {% else %}
                        <li class="disabled"><a href="#">&laquo;</a></li>
                    {% endif %}

                    {% for page in page_obj.paginator.page_range %}
                        {% if page == page_obj.number %}
                            <li class="disabled"><a href="#">{{ page }}</a></li>
                        {% else %}
                            <li class="active"><a href="{% url "r-process" %}?page={{ page }}">{{ page }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="active"><a
                                href="{% url "r-process" %}?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                    {% else %}
                        <li class="disabled"><a href="#">&raquo;</a></li>
                    {% endif %}
                </ul>
            </div>
        {% endif %}
    </div>
{% endblock %}